name: Test example code
on: [push, pull_request]
jobs:
  check-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup latest zig
        run: |
          wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
          tar xf zig-linux-x86_64-0.11.0.tar.xz
          mv zig-linux-x86_64-0.11.0 zig
      - name: Build bootstrap compiler
        run: zig/zig build
      - name: Run the test cases
        run: ./tests.sh
      - name: Build self-hosted compiler
        run: zig/zig build run -- selfhost/main.n
      - name: Disassemble the built binary
        run: objdump -d -M intel a.out
      - name: Run the built binary
        run: strace ./a.out
